// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwRxnawHaqwX7C5mquM8VQxhB-zDy3x6Y',
    appId: '1:1274533285:web:53abdce9a06543b6f1844c',
    messagingSenderId: '1274533285',
    projectId: 'my-basic-flutter',
    authDomain: 'my-basic-flutter.firebaseapp.com',
    storageBucket: 'my-basic-flutter.firebasestorage.app',
    measurementId: 'G-C6GZFYWXGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSPgJ44phyktoxxMaWkFqUH4TuT-3GSfM',
    appId: '1:1274533285:android:3ad48cb4ab9cf5a6f1844c',
    messagingSenderId: '1274533285',
    projectId: 'my-basic-flutter',
    storageBucket: 'my-basic-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCNrDcjintQcQ7cosA1C3MjqzHZNHLnG0',
    appId: '1:1274533285:ios:e9a746e53788b6ccf1844c',
    messagingSenderId: '1274533285',
    projectId: 'my-basic-flutter',
    storageBucket: 'my-basic-flutter.firebasestorage.app',
    iosBundleId: 'com.app.fullStackFlutterAppDevelopment',
  );
}
